TECH_DEBT: Deploy_All_Services Pipeline (#1484)
* Updating deploy-all pipeline with branch tag normalization

* updated pipeline

* updating normal branch name

diff --git a/Azure_Pipelines/_deploy_all_services.yml b/Azure_Pipelines/_deploy_all_services.yml
--- a/Azure_Pipelines/_deploy_all_services.yml
+++ b/Azure_Pipelines/_deploy_all_services.yml
@@ -162,45 +162,59 @@ jobs:
         healthUrl: https://$(env)-validation.nhsnlink.org/health
 
   steps:
-    - task: KubeloginInstaller@0
-      displayName: 'Install Kubelogin latest'
-      
-    - task: Bash@3
-      inputs:
-        targetType: 'inline'
-        script: |
-          GIT_COMMIT=$(git rev-parse --short HEAD)
-          echo "GIT_COMMIT: ${GIT_COMMIT}"
-          echo "##vso[task.setvariable variable=GIT_COMMIT]${GIT_COMMIT}"
+  - task: KubeloginInstaller@0
+    displayName: 'Install Kubelogin latest'
 
-    - task: Kubernetes@1
-      displayName: 'Deploy $(serviceName)'
-      inputs:
-        connectionType: 'Azure Resource Manager'
-        azureSubscriptionEndpoint: 'NHSNLink-RG ARM'
-        azureResourceGroup: '$(nhsn_resourcegroup)'
-        kubernetesCluster: '$(kube_clustername)'
-        namespace: '$(kube_namespace)'
-        command: set
-        arguments: 'image -n $(kube_namespace) deployment $(serviceName)-deploy $(containerName)=$(containerRegistry)/link-$(repoName):$(Build.SourceBranch)-$(GIT_COMMIT)'
+  - task: Bash@3
+    displayName: 'Get Git Commit'
+    inputs:
+      targetType: 'inline'
+      script: |
+        GIT_COMMIT=$(git rev-parse --short HEAD)
+        echo "GIT_COMMIT: ${GIT_COMMIT}"
+        echo "##vso[task.setvariable variable=GIT_COMMIT]${GIT_COMMIT}"
 
-    - task: Bash@3
-      displayName: 'Site Validation for $(serviceName)'
-      inputs:
-        targetType: 'inline'
-        script: |
-          echo "Starting health check for app..."
-          URL="$(healthUrl)"
-          
-          for i in {1..20}; do
-            STATUS=$(curl -s -o /dev/null -w "%{http_code}" $URL)
-            if [ "$STATUS" == "200" ]; then
-              echo "Health check succeeded with HTTP $STATUS"
-              exit 0
-            fi
-            echo "Attempt $i: App not healthy yet (HTTP $STATUS)"
-            sleep 10
-          done
-          
-          echo "Application failed health check after 10 attempts."
-          exit 1
+  - task: Bash@3
+    displayName: Normalize Branch Name
+    inputs:
+      targetType: inline
+      script: |
+        BRANCH="$(Build.SourceBranch)"
+        BRANCH=${BRANCH#refs/heads/}
+        SAFE_BRANCH_NAME=$(echo "$BRANCH" | tr '/' '-')
+        echo "Branch: $BRANCH"
+        echo "Safe Branch: $SAFE_BRANCH_NAME"
+        echo "##vso[task.setvariable variable=SAFE_BRANCH_NAME]$SAFE_BRANCH_NAME"
+
+  - task: Kubernetes@1
+    displayName: 'Deploy $(serviceName)'
+    inputs:
+      connectionType: 'Azure Resource Manager'
+      azureSubscriptionEndpoint: 'NHSNLink-RG ARM'
+      azureResourceGroup: '$(nhsn_resourcegroup)'
+      kubernetesCluster: '$(kube_clustername)'
+      namespace: '$(kube_namespace)'
+      command: set
+      arguments: 'image -n $(kube_namespace) deployment $(serviceName)-deploy $(containerName)=$(containerRegistry)/link-$(repoName):$(SAFE_BRANCH_NAME)-$(GIT_COMMIT)'
+
+  - task: Bash@3
+    displayName: 'Site Validation for $(serviceName)'
+    inputs:
+      targetType: 'inline'
+      script: |
+        echo "Starting health check for app..."
+        URL="$(healthUrl)"
+        
+        for i in {1..20}; do
+          STATUS=$(curl -s -o /dev/null -w "%{http_code}" $URL)
+          if [ "$STATUS" == "200" ]; then
+            echo "Health check succeeded with HTTP $STATUS"
+            exit 0
+          fi
+          echo "Attempt $i: App not healthy yet (HTTP $STATUS)"
+          sleep 10
+        done
+        
+        echo "Application failed health check after 20 attempts."
+        exit 1
+
